//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public int codeFaile { get; set; }
        public Nullable<int> id { get; set; }
        public string nameFiles { get; set; }
        public string linkFileCloud { get; set; }
    
        public virtual User User { get; set; }
    }
}
