//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int Payment_Code { get; set; }
        public Nullable<System.DateTime> Payment_Date { get; set; }
        public Nullable<double> Payment_Sum { get; set; }
        public Nullable<int> User_Code { get; set; }
    
        public virtual User User { get; set; }
    }
}
